name: Release app-service

on:
  push:
    branches:
      - main
      - workflow-update
    paths:
      - "pom.xml"
      - "app-service/**"

  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      IMAGE: ghcr.io/${{ github.repository }}

    steps:
      - uses: actions/checkout@v4

      - name: Extract version from pom.xml
        run: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "Version detected: $VERSION"

          VERSION_NO_SUFFIX=$(echo "$VERSION" | sed 's/-.*//')
          MAJOR=$(echo "$VERSION_NO_SUFFIX" | cut -d. -f1)
          MINOR=$(echo "$VERSION_NO_SUFFIX" | cut -d. -f2)
          PATCH=$(echo "$VERSION_NO_SUFFIX" | cut -d. -f3)

          echo "MAJOR=$MAJOR" >> $GITHUB_ENV
          echo "MINOR=$MINOR" >> $GITHUB_ENV
          echo "PATCH=$PATCH" >> $GITHUB_ENV
      

      - name: Login to GHCR
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: ./app-service
          file: ./app-service/Dockerfile
          push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
          platforms: linux/amd64,linux/arm64
          build-args: |
            MODEL_VERSION=${{ env.VERSION }}
            GITHUB_USERNAME=${{ github.actor }}
            GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
          tags: |
            ${{ env.IMAGE }}:${{ env.VERSION }}
            ${{ env.IMAGE }}:${{ env.MAJOR }}.${{ env.MINOR }}.latest
            ${{ env.IMAGE }}:${{ env.MAJOR }}.latest
            ${{ env.IMAGE }}:latest
